Product:
    type: object
    config:
        description: "Product object"
        fields:
            id:
                type: "ID!"
                description: "ID of product."
            name:
                type: "String!"
                description: "Product name."
            description:
                type: "String!"
                description: "Product description."
            promo:
                type: "Boolean!"
                description: "Determine if product is of `promo` type."
            price:
                type: "Int!"
                description: "Product price."
                args:
                    unit:
                        description: Price unit"
                        type: 'String'

            categories:
                type: "[Category]"
                description: "List of categories where product belongs."
