Query:
    type: object
    config:
        description: "Root of graphql."
        fields:
            categories:
                type: "[Category]"
                resolve: "@=resolver('categories', [args])"

            category:
                type: "Category"
                args:
                    id:
                        description: "ID of category."
                        type: "ID!"
                resolve: "@=resolver('category', [args])"

            products:
                type: "[Product]"
                args:
                    priceLessThan:
                        description: "Maximum product price."
                        type: "Int"
                    priceGreaterThan:
                        description: "Minimum product price."
                        type: "Int"
                resolve: "@=resolver('products', [args])"

            product:
                type: "Product"
                args:
                    id:
                        description: "ID of product."
                        type: "ID!"
                resolve: "@=resolver('product', [args])"
