services:
    app.graphql.resolver.character:
        class: AppBundle\GraphQL\Resolver\FooResolver
        tags:
            - { name: overblog_graphql.resolver, alias: "foo", method: "resolveFoo" }
