overblog_graphql:
    definitions:
        internal_error_message: "An error occurred, please retry later or contact us!"
        config_validation: %kernel.debug%
#        schema:
#            query: Foo
#            mutation: ~
        schema:
            query: Query
            mutation: ~
#
